### PR TITLE
french translation

### PR DESCRIPTION
**Pull request by Poussinou**
I'll rework this in the future, can you provide some screenshots of the application in french with some calendars added, I cannot use this app on my own phone...
Can you provide a screenshot of the settings in french too, some translations are ambiguous between french and english, so that I can fix them?

### CODE REVIEW

**Comment by felixwiemuth** [comment]
Thanks a lot for this quick translation! It looks pretty good and here are some screenshots so that you can improve some translations if necessary. Is the reason why you can't use the app something I can fix?

Here are a few small points I'd like you to fix before I will merge:
  - Add your copyright declaration as a second line under mine: "Copyright (C) 2016 Your Name <your_email_if_you_want>"
  - I changed the string welcome_message, please update
  - I made the string app_name untranslatable (I guess this means you should remove it from the translation)
  - Sometimes you set the colon ":" incorrectly with a space in front, please correct that
  - Maybe "Autoriser" is not appropriate as it's actually about enabling/disabling and not allowing
  - Finally rebase your changes onto my master branch
  
In case you are considering to do translations of the [Help](https://github.com/felixwiemuth/LinCal/blob/master/app/src/main/res/raw/help.html) and [About](https://github.com/felixwiemuth/LinCal/blob/master/app/src/main/res/raw/about.html) pages, I should say that they might change quite a bit with the next versions. Nonetheless, at least for the Help page a translation should be reusable for later versions.
Unfortunately there is also content in the app/src/main/assets folder, where it is more complicated with localization but for now it's only the "Open source licenses" dialog which could use a translation but it doesn't have to.

Further there is an acknowledgments section in the about page where I'd also like to mention your translation, please tell me what name/email I should use for you.

Thanks again!

screenshot_20161230-202402
screenshot_20161230-202414
screenshot_20161230-202449
screenshot_20161230-203133
screenshot_20161230-213054
screenshot_20161230-203145
screenshot_20161230-203218

**Comment by Poussinou** [comment]
I will have a look this week-end ;-)

**Comment by Poussinou** [comment]
Thanks for the screenshots, all the translations I did were good :)
I assume I have to put my copyright declaration in the README.md, so I did it.
In French, we put a space in front of all the semi-colons we use, in every case, I know it's not the case in English, that's why I just put them in the French translation, but I can remove them if you really want...
Please tell me how I can translate the Help and About pages, I will do it. When there will have some new translations to do, just notify me, I'll do it if I have the time ! :)

For the acknowledgements section, just put my github pseudo Poussinou and a link to my github page https://github.com/Poussinou if you want.

**Comment by felixwiemuth** [comment]
Okay, thanks for continuing.
Regarding the copyright, sorry my advice was a bit ambiguous, actually I meant that you should put it in the header of `strings.xml` and not in `README.md` (instead I will add a `CONTRIBUTORS` file where you are mentioned).
I didn't know about the space in French, if this is the way one usually expects it to appear in an app then you should leave it like that.
If you want, you can translate Help and About (both are in the [raw](https://github.com/felixwiemuth/LinCal/blob/master/app/src/main/res/raw/) folder). To do so, do the same as with values: just create a folder `raw-fr` (the localization works for all folders in the res folder). Do not translate the text in the license section of the About page.
For the coming release I did a few further changes to `strings.xml`, it would be nice if you could update the translation.

**Comment by Poussinou** [comment]
@felixwiemuth everything should be good now
Notify me for new translations

**Comment by felixwiemuth** [comment]
@Poussinou
Thank you again a lot for updating the translations and even translating Help and About. I did not incorporate them yet because I wanted to include some more things in the new release, which took some time but now it's ready soon. There were a few updates to translated files since, so it would be nice to have them reflected in the translations before the release. I added a section in README with instructions for translating, please check whether your translations correspond to those. Sorry for letting you update again before finally including them but I hope you see the point. I added an issue for you: #6 .

**Pull request closed without merging**
