### PR TITLE
Updated de (German) translation

### PR DESCRIPTION
**Pull request by jaller94**
Commit made via Stringlate

### CODE REVIEW

**Comment by jaller94** [comment]
Beware, I'm not sure Stringlate always knows what it is doing to the xml.

**Comment by felixwiemuth** [comment]
Thank you for wanting to translate LinCal. Have you read the instructions regarding translations in Readme? German was already on the list of planned translations, but nevermind, your formulations might help anyway. As there are some flaws (e.g. the `changelog_*` strings should be translated and I would change some wordings) I will probably create a new version of the translation and use yours as inspiration. If you like I will add your name, email and/or link to Github account to the places where contributors are mentioned, as specified in Readme (please tell me what you prefer).

**Comment by jaller94** [comment]
Yep, do with it whatever you want - my main interest is to get the German translation done. I am aware that you could have translated it yourself.
Credits are not required, however it would be nice to link to my GitHub.

**Comment by felixwiemuth** [comment]
Okay. At the moment I am working on adding localization to [LinearFileParser](https://github.com/felixwiemuth/LinearFileParser) so that error messages from reading calendar files will also be translated. Then I will add the German translation to LinCal. It will be available with the next update which will be published in around two weeks.

**Pull request closed without merging**
